spring:
  application:
    name: stockMate

  datasource:
    url: jdbc:postgresql://localhost:26257/postgres
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        web: debug
        security: TRACE
      hibernate:
        jpa: debug
        jdbc: debug
    com:
      zkollonay:
        moneymate: debug
